### ISSUE TITLE
Can't see nodes in dynamo 2.0.2

### ISSUE THREAD

**Issue by davidmleearup** [DynamoDS/Dynamo#10248]
Dynamo 2.2

Windows 10 with Revit 2019

I try to open an existing dynamo script, and the nodes are not showing up.

![image](https://user-images.githubusercontent.com/59261723/71484853-22e1e100-27d4-11ea-8727-cf9e7537d6b6.png)

**Comment by QilongTang** [comment]
@mjkkirschner Did we fixed this bug in the very recent Dynamo version?

**Comment by davidmleearup** [comment]
No, never got any fix. I had been using 1.3 version. Any dynamo with 2.0 version cannot be worked on due to this bug.

Best Regards,
David Lee  E.I.T
Graduate Engineer | Mechanical

Arup
35 East Wacker Drive  Suite 1800  Chicago  IL  60601  USA
t: +1 312 849 5610  d: +1 312 849 6360
m: +1 312 919 7119
www.arup.com

**Comment by mjkkirschner** [comment]
Hi @davidmleearup please see this thread:
https://github.com/DynamoDS/Dynamo/issues/10118

we have done what is currently possible to fix this, but you should be able to work around it in most cases by removing conflicting revit addins or removing the `system.windows.interactivity.dll` files from Dynamo's core folder.

**Comment by davidmleearup** [comment]
Do you know what the “conflicting addins” are? How could I distinguish that an addin is conflicting? I don’t want to delete all the addins I have.

I had tried removing the dll file you specified but did not fix the issue.

Best Regards,
David Lee  E.I.T
Graduate Engineer | Mechanical

Arup
35 East Wacker Drive  Suite 1800  Chicago  IL  60601  USA
t: +1 312 849 5610  d: +1 312 849 6360
m: +1 312 919 7119
www.arup.com
