### ISSUE TITLE
Absturzbericht von Dynamo 2.5.0.7460

### ISSUE THREAD

**Issue by OlafKammler** [DynamoDS/Dynamo#10676]
# Issue Description
Still not working Plugins of Dynamo
![image](https://user-images.githubusercontent.com/59934637/82315815-2caaf180-99cc-11ea-9a5a-f9da28c02065.png)

### What did you do?
I updated to the latest version of Revit 2021. Generative Design appears again.

### What did you expect to see?
All notification should be gone after the update.

### What did you see instead?
Still notification.
![image](https://user-images.githubusercontent.com/59934637/82315815-2caaf180-99cc-11ea-9a5a-f9da28c02065.png)

### What packages or external references (if any) were used?
Just opened Dynamo after the update of Revit.

### Stack Trace
```
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
```

---
OS: `Microsoft Windows NT 10.0.18363.0`
CLR: `4.0.30319.42000`
Dynamo: `2.5.0.7460`
Revit: `21.0.0.383 20200220_1100(x64)`

**Comment by Amoursol** [comment]
@saintentropy Any thoughts here?

**Comment by saintentropy** [comment]
@OlafKammler I think that you need to update the Refinery Toolkit Package.  This package is not directly installed by our GD Update but it is used in some of the samples.  Version 1.1.0 was trying to load its components twice which caused the warnings.  The package version 1.1.1 should fix this issue and the erroneous errors you are seeing should go away.  Try that and let us know if that fixes the issue your seeing

**Comment by OlafKammler** [comment]
@saintentropy thanks for your quick reply. I installed the newer package 1.1.1. Notifications were still shown. I checked the package folder and deleted "Refinery Toolkit for Space Planning 1.0.0" and "Refinery Toolkit for Massing in Revit 1.0.1". After restart, the notifications are gone. Problem solved. No double loading of the packages anymore. Thanks!
