### ISSUE TITLE
Code Block inactive

### ISSUE THREAD

**Issue by sueeehadi** [DynamoDS/Dynamo#7130]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.1.0.2094
## Operating system

Windows 10
## What did you do?

Code block
## What did you expect to see?

Code block greyed out without me being able to write a code
## What did you see instead?

Greyed out inactive block
![image](https://cloud.githubusercontent.com/assets/22092965/18377962/9d4bf99a-769c-11e6-8b43-643298e533f9.png)

**Comment by sharadkjaiswal** [comment]
@sueeehadi, do you remember the steps to reproduce this problem? What happens when you save this graph and open it again?

**Comment by sueeehadi** [comment]
@sharadkjaiswal It was working fine up till a few moments ago.. 
I did every other thing I could, restarting both Revit 17 and Dynamo. Copying the graph and saving it under a new name, restarting my PC. Nothing seems to be working.

**Comment by sharadkjaiswal** [comment]
So even after saving and closing Dynamo, Code Block is un-editable. Can you create a new code block on a new graph? If possible, can you please pass me your DYN file, so that I can investigate?

**Comment by sueeehadi** [comment]
@sharadkjaiswal on all graphs the code block was un-editable. Old or new. Told my IT guy to help me to uninstall and reinstall it once again. The issue was, I have 2 dynamo versions on my PC. After the older version was removed, it works fine. I guess having the 2 versions is a timely trigger for screwing up the application.

**Comment by sharadkjaiswal** [comment]
@sueeehadi great to know that it got sorted out, do you mind sharing the version number of the two different Dynamo? We can document that in our readme, so that others won't get into this issue.

**Comment by sueeehadi** [comment]
1.1.0.2094 and 0.9

**Comment by mrenaud8** [comment]
I just had the same problem with upgrading to 1.1.0.2094 from 1.0 running windows 7pro. so from reading my understanding is that if 2 versions install on one pc it makes nodes not function correctly?

**Comment by sueeehadi** [comment]
@mrenaud8 well, in my case yeah. I had two versions installed and it screwed up my nodes. There was nothing I could do to retrieve the functional nodes. It worked well after uninstalling the older version. strange though, we were told that there shouldn't be any interfacing issues despite having more then 1 version installed.

**Comment by jnealb** [comment]
This is tracked with MAGN-10678

**Comment by QilongTang** [comment]
Fixed in https://github.com/DynamoDS/DynamoRevit/pull/1309

**Comment by DanielHurtubise** [comment]
Revit 2017.1
Dynamo & Dynamo Core 1.2.0.2690
Windows 10x64 ENU

Code block are greyed out and i have no other version installed.

**Comment by jnealb** [comment]
You need the 1.2.0.2831 release for the cbn fix.

**Comment by DanielHurtubise** [comment]
Just installed the latest build (1.2.1.3083) and i still have the same problem. Dynamo Studio Code Block works fine but not in Revit.
I would really love to figure it out.

**Comment by jnealb** [comment]
@DanielHurtubise Can you please check that the About box in D4R really shows 1.2.1.3083?

**Comment by DanielHurtubise** [comment]
Morning,
now showing 1.2.1.3083 :)

Feel free to email me if you want access to my system (dhurtubise   @   rpbw    .   com)
Cheers
And sorry for the delay between AU and back in Paris :(

**Comment by mjkkirschner** [comment]
hey @DanielHurtubise - can you please make sure to totally remove all older versions of both DynamoRevit and Dynamo core before reinstalling?

**Comment by DanielHurtubise** [comment]
I can do that again, no worries ;)
1 - Anything the uninstaller won't pickup that i should be aware?
2- Any specific version i should reinstall?

Thanks

**Comment by QilongTang** [comment]
@DanielHurtubise I am testing your case in a clean VM. I am looking at Windows 7, with only Revit2017.1 installed which comes with Dynamo 1.2.1.3083 correct? Any steps you would like to share, did you see CBN uneditable just opening Dynamo?

**Comment by DanielHurtubise** [comment]
It's Windows 10 x64 (1607 build 14393.447) for the record :)

yes Code Blocks are uneditable at the start. I did offer @kronz to setup a remote access, wouldn't it be easier? :)

Thanks for the help

**Comment by jnealb** [comment]
@DanielHurtubise @QilongTang It would be, do you use TeamViewer? I installed Dynamo 1.2.1.3083 ontop of Revit 2017 (Build 17.0.499.0 20160714_1515(x64)) in a Win10 VM and the CBN nodes are fine.

**Comment by DanielHurtubise** [comment]
Yes i do use TeamViewer but you have to keep in my mind the time difference, im in Paris :)

**Comment by jnealb** [comment]
c'est rien compared to Singapore

**Comment by DanielHurtubise** [comment]
ahahahah Good morning @jnealb Im in the office, let me know if you want to look at the issue :)

**Comment by jnealb** [comment]
Sorry today is not good, can do it tomorrow 8:00am or 11:00am EST?

**Comment by jnealb** [comment]
@DanielHurtubise @QilongTang Actually my colleague Aaron and I are available Thu 8:00am EST. Would this be convenient for you for a TeamViewer session?

**Comment by DanielHurtubise** [comment]
Of course, i will be in don't worry :)
Thanks a lot again guys

**Comment by DanielHurtubise** [comment]
Anytime you guys want ;) dhurtubise   AT   RPBW   DOT COM :)

**Comment by jnealb** [comment]
J'arrive dabs 45mns; je suis encode au metro :)
________________________________

**Comment by jnealb** [comment]
Hi Daniel,

Aaron and I are ready. Is this a good time?

Neal

**Comment by jnealb** [comment]
@DanielHurtubise We have a meeting in 30mns, please let us know.

**Comment by jnealb** [comment]
Please see https://forum.dynamobim.com/t/dead-code-block-nodes-in-d4r/8132 for a workaround.
