### ISSUE TITLE
Dynamo 2.0: The dictionary conundrum with ZT multi-port outputs 

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/Dynamo#8665]
## Dynamo version

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)
![image](https://user-images.githubusercontent.com/18601851/37567914-ced0e1c2-2ac5-11e8-82ea-1f67718a2b19.png)

## Operating system

Win10

## What did you do? 

Observed the following issues with the new dictionary implementation in V2.0 in relation to ZT multi-port outputs.

**Issue 1:**
The objects string representation shows only 'Dictionary' which is a noticeable departure from the watch window (the one directly accessible from the node) in previous versions, and is not very useful to users as they cant see the values nor the keys without the addition of Watch nodes:
![image](https://user-images.githubusercontent.com/18601851/37567963-72efe01e-2ac6-11e8-9093-21370edc889b.png)

For example, I would expect to see this, which leads to the second issue:
![image](https://user-images.githubusercontent.com/18601851/37567977-b247747a-2ac6-11e8-9380-f4ce2ef8c68b.png)

**Issue 2**
Dictionaries are unordered collections, but that introduces a new problem to users familiar with how Dynamo displays the string output in previous versions, as the order of the value keys no longer align with the order of the output ports - I would expect this to cause a lot of confusion to those still learning the ropes:
![image](https://user-images.githubusercontent.com/18601851/37568030-7ed29164-2ac7-11e8-83b8-4f692d305773.png)

**Conundrum:**
Strictly speaking, multi-port ZT nodes are a bit of an anomaly as the dictionary values are rerouted to singletons or lists then output by the nodes ports (albeit, only in the visual programming environment), meaning the return type is not a dictionary. Another way to frame it would be "_how can I get the dictionary object from a multi-port ZT node_". The answer is, you cant, because of this behaviour, so why show the string representation as 'Dictionary'?

Technically then, the return type shown here is wrong:
![image](https://user-images.githubusercontent.com/18601851/37568086-5662239c-2ac8-11e8-9eb6-cf8ee3e343f9.png)

But of course, in the text-based programming environment, the return type is the expected type (i.e. a dictionary):

![image](https://user-images.githubusercontent.com/18601851/37568104-756e92ca-2ac8-11e8-9029-668f6e8fbc0f.png)

The conundrum then is how to represent the differing return types based on the context.

Since this is already an anomaly, my suggestion would be to keep the existing behavior of multi-port ZT nodes unchanged in the node/visual programming environment (i.e. output a list of lists and ensure the string representation also shows this) as the latest behavior is contradictory. Where it starts getting awkward is in situations where a user starts with the node version and sees a list, then does node to code or calls the same ZT node in DS, and is confronted by an inconsistent philosophy regarding return types as they will see a dictionary instead.

**Comment by aparajit-pratap** [comment]
@ThomasMahon thanks for your observations. In Issue 1 are you indicating that  you are unable to expand the node preview because if you cannot it is a bug. In the case of multi-output nodes we do arrange the keys in the Dictionary to follow the same order as that of the output ports (in the event that you are able to expand the preview, i.e.). We cannot however guarantee that ordering for code block nodes because the multi-outport information is missing.

**Comment by ThomasMahon** [comment]
@aparajit-pratap yes, it wont expand. I thought that was as-designed, but clearly not, so that must be a bug then. 

On point two, i saw in daily build version 2.0.0.3766 that unfortunately the dictionary keys do not match the output ports:

![image](https://user-images.githubusercontent.com/18601851/37880482-03890690-3081-11e8-91ec-1a1088367f93.png)

**Comment by jnealb** [comment]
@ThomasMahon @aparajit-pratap Thank you for your reports - firstly we note that you are using an older version of 2.0 which does not include some of the latest language changes re: list syntax changes from {} to []. So can you please upgrade to the latest daily build. Note that you will have to update your node inputs using default arguments from {} to []. Please see https://github.com/DynamoDS/Dynamo/issues/8604. Also this older build may not have the output node re-ordering that we implemented in #8487, as mentioned above. And finally we could not reproduce the node preview not expanding with other multi-output nodes (Revit or otherwise) if you still have this issue could you provide us with your Revit model so that we can reproduce it as described above.

**Comment by ThomasMahon** [comment]
@jnealb I still have the same problem with the unexapnded watch window with todays daily:

![image](https://user-images.githubusercontent.com/18601851/38370855-0b360950-38e3-11e8-8cc8-451fb783602e.png)

![image](https://user-images.githubusercontent.com/18601851/38370871-15a123fc-38e3-11e8-87d0-55becec09326.png)

I've simply created a fresh 2018.2 Arch model from the default Arch template, linked in a DWG then wired up the Bimorph node. I tested in 2017.2 and observe the same problem.

**Comment by aparajit-pratap** [comment]
@jnealb could you verify and log this bug.

**Comment by mjkkirschner** [comment]
@ThomasMahon is CAD.CurvesFromCADLayers a nodeModel based node where you implemented BuildOutputAST?

**Comment by jnealb** [comment]
@ThomasMahon @aparajit-pratap @mjkkirschner This is tracked with QNTM-3947.

**Comment by ThomasMahon** [comment]
@mjkkirschner its a simple ZT node

**Comment by aparajit-pratap** [comment]
@ThomasMahon the bug with the Dictionary preview not expanding has been fixed. There will still remain an inconsistency between code block node previews and multi-return UI node previews for Dictionaries as discussed. Closing issue.
